spring:
  datasource:
    validationQuery: SELECT 1
    url: jdbc:mysql://127.0.0.1:3306/crawler?relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&autoReconnect=true
    username: root
    password: passw0rd
    #driver-class-name: com.mysql.jdbc.Driver
  jpa:
#    show_sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

fileDownloader:
  storagePath: download-file/
  threadNum: 20